wolf_controller:
  ubuntu:
    xenial: ros-kinetic-wolf-controller
    bionic: ros-melodic-wolf-controller
    focal:  ros-noetic-wolf-controller
wolf_controller_utils:
  ubuntu:
    xenial: ros-kinetic-wolf-controller-utils
    bionic: ros-melodic-wolf-controller-utils
    focal:  ros-noetic-wolf-controller-utils
wolf_gazebo_interface:
  ubuntu:
    xenial: ros-kinetic-wolf-gazebo-interface
    bionic: ros-melodic-wolf-gazebo-interface
    focal:  ros-noetic-wolf-gazebo-interface
wolf_gazebo_resources:
  ubuntu:
    xenial: ros-kinetic-wolf-gazebo-resources
    bionic: ros-melodic-wolf-gazebo-resources
    focal:  ros-noetic-wolf-gazebo-resources
wolf_hardware_interface:
  ubuntu:
    xenial: ros-kinetic-wolf-hardware-interface
    bionic: ros-melodic-wolf-hardware-interface
    focal:  ros-noetic-wolf-hardware-interface
sensors_description:
  ubuntu:
    xenial: ros-kinetic-sensors-description 
    bionic: ros-melodic-sensors-description 
    focal:  ros-noetic-sensors-description
teleop_description:
  ubuntu:
    xenial: ros-kinetic-teleop-description
    bionic: ros-melodic-teleop-description
    focal:  ros-noetic-teleop-description
anymal_description:
  ubuntu:
    xenial: ros-kinetic-anymal-description
    bionic: ros-melodic-anymal-description
    focal:  ros-noetic-anymal-description
anymalc_description:
  ubuntu:
    xenial: ros-kinetic-anymalc-description
    bionic: ros-melodic-anymalc-description
    focal:  ros-noetic-anymalc-description
hyq_description:
  ubuntu:
    xenial: ros-kinetic-hyq-description
    bionic: ros-melodic-hyq-description
    focal:  ros-noetic-hyq-description
aliengo_description:
  ubuntu:
    xenial: ros-kinetic-aliengo-description
    bionic: ros-melodic-aliengo-description
    focal:  ros-noetic-aliengo-description
teleop_description:
  ubuntu:
    xenial: ros-kinetic-teleop-description
    bionic: ros-melodic-teleop-description
    focal:  ros-noetic-teleop-description
spot_description:
  ubuntu:
    xenial: ros-kinetic-spot-description
    bionic: ros-melodic-spot-description
    focal:  ros-noetic-spot-description
solo_description:
  ubuntu:
    xenial: ros-kinetic-solo-description
    bionic: ros-melodic-solo-description
    focal:  ros-noetic-solo-description
ylo2_description:
  ubuntu:
    xenial: ros-kinetic-ylo2-description
    bionic: ros-melodic-ylo2-description
    focal:  ros-noetic-ylo2-description
go1_description:
 ubuntu:
    xenial: ros-kinetic-go1-description
    bionic: ros-melodic-go1-description
    focal:  ros-noetic-go1-description
kinova_description:
  ubuntu:
    xenial: ros-kinetic-kinova-description
    bionic: ros-melodic-kinova-description
    focal:  ros-noetic-kinova-description
wolf_description_utils:
  ubuntu:
    xenial: ros-kinetic-wolf-description-utils
    bionic: ros-melodic-wolf-description-utils
    focal:  ros-noetic-wolf-description-utils
wolf_rviz_plugin:
  ubuntu:
    xenial: ros-kinetic-wolf-rviz-plugin
    bionic: ros-melodic-wolf-rviz-plugin
    focal:  ros-noetic-wolf-rviz-plugin
wolf_navigation_utils:
  ubuntu:
    xenial: ros-kinetic-wolf-navigation-utils
    bionic: ros-melodic-wolf-navigation-utils
    focal:  ros-noetic-wolf-navigation-utils
task_exploration:
  ubuntu:
    xenial: ros-kinetic-task-exploration
    bionic: ros-melodic-task-exploration
    focal:  ros-noetic-task-exploration
task_waypoints:
  ubuntu:
    xenial: ros-kinetic-task-waypoints
    bionic: ros-melodic-task-waypoints
    focal:  ros-noetic-task-waypoints
task_homing:
  ubuntu:
    xenial: ros-kinetic-task-homing
    bionic: ros-melodic-task-homing
    focal:  ros-noetic-task-homing
task_interface:
  ubuntu:
    xenial: ros-kinetic-task-interface
    bionic: ros-melodic-task-interface
    focal:  ros-noetic-task-interface
rt_logger:
  ubuntu:
    xenial: ros-kinetic-rt-logger
    bionic: ros-melodic-rt-logger
    focal:  ros-noetic-rt-logger 
rt_gui:
  ubuntu:
    xenial: ros-kinetic-rt-gui
    bionic: ros-melodic-rt-gui
    focal:  ros-noetic-rt-gui
ai_utils_msgs:
  ubuntu:
    xenial: ros-kinetic-ai-utils-msgs
    bionic: ros-melodic-ai-utils-msgs
    focal:  ros-noetic-ai-utils-msgs
wolf_msgs:
  ubuntu:
    xenial: ros-kinetic-wolf-msgs
    bionic: ros-melodic-wolf-msgs
    focal:  ros-noetic-wolf-msgs
wolf_estimation:
  ubuntu:
    xenial: ros-kinetic-wolf-estimation
    bionic: ros-melodic-wolf-estimation
    focal:  ros-noetic-wolf-estimation
wolf_nvga:
  ubuntu:
    xenial: ros-kinetic-wolf-nvga
    bionic: ros-melodic-wolf-nvga
    focal:  ros-noetic-wolf-nvga
nimbro_cam_transport:
  ubuntu:
    xenial: ros-kinetic-nimbro-cam-transport
    bionic: ros-melodic-nimbro-cam-transport
    focal:  ros-noetic-nimbro-cam-transport
nimbro_log_transport:
  ubuntu:
    xenial: ros-kinetic-nimbro-log-transport
    bionic: ros-melodic-nimbro-log-transport
    focal:  ros-noetic-nimbro-log-transport
nimbro_service_transport:
  ubuntu:
    xenial: ros-kinetic-nimbro-service-transport
    bionic: ros-melodic-nimbro-service-transport
    focal:  ros-noetic-nimbro-service-transport
nimbro_topic_transport:
  ubuntu:
    xenial: ros-kinetic-nimbro-topic-transport
    bionic: ros-melodic-nimbro-topic-transport
    focal:  ros-noetic-nimbro-topic-transport
